spring:
  config:
    import:
      - classpath:/yml/application-prod.yml
      - classpath:/yml/application-dev.yml
      - classpath:/yml/application-qa.yml
      - classpath:/yml/logging/application-log.yml
  profiles:
    group:
      logging: dev, log
    active: logging
#    active: local